### ISSUE TITLE
media are wrongly saved on db

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#112] opened 2015-06-03 14:50 UTC
# What occurs
I've created an article including a media. I've observed on db that the media record is duplicated on db

> db.items.find({"_id": ObjectId("556f126c9a645d2511d7fd03")})
**{ "0" : { "type" : "application/pdf", "length" : NumberLong(137710558), "title" : "Building Service", "url" : "https://drive.google.com/uc?export=download&id=0Bzfx1cNAAzhsTTM4UVdZaFRrS0E" }**, "_id" : ObjectId("556f126c9a645d2511d7fd03"), "author" : "", "created" : ISODate("2015-06-03T14:42:52.260Z"), "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. ", "groups" : [ ], "guid" : "", "is_published" : true, "link" : "", **"medias" : [      {       "type" : "application/pdf",   "length" : NumberLong(137710558),  "title" : "Building Service",    "url" : "https://drive.google.com/uc?export=download&id=0Bzfx1cNAAzhsTTM4UVdZaFRrS0E" } ]**, "modified" : ISODate("2015-06-03T14:43:37.362Z"), "order" : NumberLong(4), "parent_id" : NumberLong(7120), "pubdate" : ISODate("2015-06-03T14:42:52.260Z"), "published" : ISODate("2015-06-03T14:41:00Z"), "site_id" : NumberLong(462), "thumbnails" : [    {       "width" : "80",         "height" : "60",        "url" : "http://meumobi.com/uploads/items/80x60_6800361.jpg" },     {       "width" : "80",         "height" : "80",   "url" : "http://meumobi.com/uploads/items/80x80_6800361.jpg" },  {       "width" : "139",        "height" : "139",  "url" : "http://meumobi.com/uploads/items/139x139_6800361.jpg" },        {       "width" : "314",        "height" : "220",   "url" : "http://meumobi.com/uploads/items/314x220_6800361.jpg" } ], "title" : "Building Service (Vidéo)", "type" : "articles" }
```

# How to reproduce
Create an article including a media and check the db record on mongo.

**Comment by t4deu** [comment] 2015-06-03 17:18
I think there was a ticket on gopllan about this, It was something about how lithiun persists the objects

**Comment by t4deu** [comment] 2015-07-10 19:16
I can't reproduce creating/updating an article including a media and checking the db record on mongo. I will do more tests

**Comment by juliogreff** [comment] 2015-07-14 18:58
@t4deu any news on this? Can we close it or still needs fixing?

**Comment by elbidone** [comment] 2015-07-15 01:54
I also didn't reproduce it. It strange because no new release have been deployed since I've opened it.
I close it as "couldn't reproduce"

**Comment by elbidone** [comment] 2015-07-22 15:57
You can reproduce this issue importing following feed:
http://enterprise.meumobilesite.com/docs/feed.xml

It will render following json through API, which create unexpected "0" and "1" keys containing media duplicated:
http://infobox.meumobilesite.com/api/deloitte.meumobi.com/items/latest?limit=50

**Comment by t4deu** [comment] 2015-07-22 20:34
I managed to reproduce the error using the feed.
But can't find the cause of the bug.
I checked the item before and after being imported, also tried to loading the item after it be saved.
But the item did not have any problem.

Only  after the import end I could see the error in the database.

**Comment by t4deu** [comment] 2015-07-22 21:39
First occurrences by servers:
INT:
```
> db.items.find({0: { $exists: true}},{created:1,site_id:1}).sort({created: 1});
{ "_id" : ObjectId("545a2353b5a50835268b458e"), "created" : ISODate("2013-09-30T22:00:00Z"), "site_id" : NumberLong(5) }
```
PROD:
```
> db.items.find({0: { $exists: true}},{created:1,site_id:1}).sort({created: 1});
{ "_id" : ObjectId("50bb439d303701cd52000000"), "created" : ISODate("2012-12-02T12:03:41.500Z"), "site_id" : NumberLong(61) }
```

CSE:
> //can't log in on the CSE server, TIMEOUT error

**Comment by elbidone** [comment] 2015-07-22 21:55
Check if this issue is not due to item.thumbnails implementation.

**Comment by t4deu** [comment] 2015-07-23 18:39
I can't find the commit that included the item.thumbnails feature, but removing the feature don't fixed the issue

**Comment by t4deu** [comment] 2015-07-23 18:40
I managed to reproduce the error on servers INT, PROD, RIMOBI and LOCAL using the feed:
> http://enterprise.meumobilesite.com/docs/feed.xml

**Comment by t4deu** [comment] 2015-07-23 19:49
Feeds with the issue by server:
INT:
```
> db.extensions.find({category_id:{$in:categories}},{category_id:1,url:1});
{ "_id" : ObjectId("545a20cdb5a508da1f8dadff"), "category_id" : NumberLong(22), "url" : "http://services.int-meumobi.com/docs/tests/video-rss-sample.xml" }
{ "_id" : ObjectId("545a2166b5a508453b8dadff"), "category_id" : NumberLong(24), "url" : "http://www.lerugbynistere.fr/rss-meumobil.php" }
{ "_id" : ObjectId("545a231fb5a508da1f8dae00"), "category_id" : NumberLong(25), "url" : "http://services.int-meumobi.com/docs/tests/santander-resultados.xml" }
{ "_id" : ObjectId("545a256eb5a508453b8dae00"), "category_id" : NumberLong(26), "url" : "http://services.int-meumobi.com/docs/tests/rss-sample.xml" }
{ "_id" : ObjectId("545a2b75b5a508821c8dadff"), "category_id" : NumberLong(27), "url" : "http://www.lerugbynistere.fr/rss-meumobil.php" }
{ "_id" : ObjectId("5553581eb5a5081f508b4567"), "category_id" : NumberLong(53), "url" : "http://feeds.feedburner.com/NoticiasINFO-Mercado" }
{ "_id" : ObjectId("55a55bc2b5a5084b638b4567"), "category_id" : NumberLong(58), "url" : "http://enterprise.meumobilesite.com/docs/feed.xml" }

```
RIMOBI:
```
> db.extensions.find({category_id:{$in:categories}},{category_id:1,url:1});
{ "_id" : ObjectId("55b133b7701796403e8b4567"), "category_id" : 472, "url" : "http://enterprise.meumobilesite.com/docs/feed.xml" }
{ "_id" : ObjectId("535fe9a070179618475fe5e9"), "category_id" : 67, "url" : "feed://ri.santander.com.br/xml.aspx?idCanal=fkkklGpEnAXNWICTpEW2UQ==&linguagem=en" }
{ "_id" : ObjectId("5388b205701796ac408b4567"), "category_id" : 170, "url" : "http://ri.embraer.com.br/FeedMeuMobi.aspx?idCanal=GHSVkh17Mf9OzMsR3YK6wg==" }
{ "_id" : ObjectId("544f8d4f7017969b1988e175"), "category_id" : 271, "url" : "http://www.renewableenergyworld.com/rss/other-technology.rss" }
{ "_id" : ObjectId("5361169270179691118b4567"), "category_id" : 86, "url" : "http://ri.santander.com.br/xml.aspx?idCanal=6p1rWZJg/bmGJjjeNvtYLQ==&tp=0" }
{ "_id" : ObjectId("5596e6fe7017964d508b4568"), "category_id" : 469, "url" : "http://ri.santander.com.br/xml.aspx?idCanal=s0UvSVPXwHeLDEOqqAt4PQ==&linguagem=en" }

```
PROD:
```
> db.extensions.find({category_id:{$in:categories}},{category_id:1,url:1});
{ "_id" : ObjectId("50eaf4c6303701402c00000a"), "category_id" : 607, "url" : "http://www.mobilepedia.com.br/feed" }
{ "_id" : ObjectId("50be2e89303701f10e00001f"), "category_id" : 446, "url" : "http://revistaveuegrinalda.com.br/home/?feed=rss2" }
{ "_id" : ObjectId("537399789a645d0c0c000000"), "category_id" : 1662, "url" : "http://brazil.worldcupblog.org/feed" }
{ "_id" : ObjectId("53776ef79a645d4732000000"), "category_id" : 1671, "url" : "http://maonarodablog.com.br/feed/" }
{ "_id" : ObjectId("53b6b2af9a645d6610000000"), "category_id" : 7017, "url" : "http://services.int-meumobi.com/docs/media.xml" }
{ "_id" : ObjectId("53b6b85a9a645de91a000000"), "category_id" : 7020, "url" : "http://www.lemonde.fr/coupe-du-monde/rss_full.xml" }
{ "_id" : ObjectId("53c9391f9a645d8d14000000"), "category_id" : 7029, "url" : "http://branca.ipanemax.com/static/news-surf.xml" }
{ "_id" : ObjectId("53e2db789a645d7c0b000000"), "category_id" : 7042, "url" : "http://blog.dino.com.br/feed/" }
{ "_id" : ObjectId("53ee1d7f9a645dc76c000000"), "category_id" : 7064, "url" : "http://www.simonealine.com/feeds/posts/default?alt=rss" }
{ "_id" : ObjectId("53f253db9a645d7278000000"), "category_id" : 7071, "url" : "http://vidaplasc.com.br/feed/rss2" }
{ "_id" : ObjectId("50bb43cc303701cd52000014"), "category_id" : 410, "url" : "http://api.flickr.com/services/feeds/photos_public.gne?id=52425325@N02&lang=en-us&format=rss_200" }
{ "_id" : ObjectId("50bddb37303701f43c000014"), "category_id" : 433, "url" : "http://api.flickr.com/services/feeds/photos_public.gne?id=32951986@N05&lang=en-us&format=rss_200" }
{ "_id" : ObjectId("50be18fe303701f10e000014"), "category_id" : 445, "url" : "http://api.flickr.com/services/feeds/photos_public.gne?id=32951986@N05&lang=en-us&format=rss_200" }
{ "_id" : ObjectId("50be2ed8303701e627000014"), "category_id" : 447, "url" : "http://api.flickr.com/services/feeds/photos_public.gne?id=32951986@N05&lang=en-us&format=rss_200" }
{ "_id" : ObjectId("50c1c51a3037012633000014"), "category_id" : 460, "url" : "http://api.flickr.com/services/feeds/photos_public.gne?id=32951986@N05&lang=en-us&format=rss_200" }
{ "_id" : ObjectId("50c9d7153037019611000014"), "category_id" : 481, "url" : "http://api.flickr.com/services/feeds/photos_public.gne?id=32951986@N05&lang=en-us&format=rss_200" }
{ "_id" : ObjectId("50ef2824303701455e00000a"), "category_id" : 635, "url" : "http://www.mobilepedia.com.br/feed" }
{ "_id" : ObjectId("510a76d09a645d1249000014"), "category_id" : 732, "url" : "http://api.flickr.com/services/feeds/photos_public.gne?id=32951986@N05&lang=en-us&format=rss_200" }
{ "_id" : ObjectId("5113e5e59a645db941000010"), "category_id" : 793, "url" : "http://api.flickr.com/services/feeds/photoset.gne?set=72157628400768435&nsid=45815025@N04&lang=pt-br" }
{ "_id" : ObjectId("5113e5e99a645db142000000"), "category_id" : 793, "url" : "http://api.flickr.com/services/feeds/photoset.gne?set=72157628400768435&nsid=45815025@N04&lang=pt-br" }
{ "_id" : ObjectId("511501e29a645dbf0d00000a"), "category_id" : 812, "url" : "http://www.onehealthmag.com.br/index.php/feed/" }
{ "_id" : ObjectId("5256e2479a645dfa5a000000"), "category_id" : 1401, "url" : "http://www.blog.agenciadoor.com.br/" }
{ "_id" : ObjectId("52c1aada9a645d5d04000000"), "category_id" : 1506, "url" : "http://www.sochi2014.com/en/media/news/rss/" }
{ "_id" : ObjectId("537399d19a645d660b000000"), "category_id" : 1664, "url" : "http://www.theguardian.com/football/world-cup-2014-qualifiers/rss" }
{ "_id" : ObjectId("53eafaed9a645d7c4a000000"), "category_id" : 7061, "url" : "http://services.int-meumobi.com/docs/tests/santander-resultados.xml" }
{ "_id" : ObjectId("54354b789a645dab55000000"), "category_id" : 7082, "url" : "http://services.int-meumobi.com/docs/tests/video-rss-sample.xml" }
{ "_id" : ObjectId("555e27649a645dff69c57d89"), "category_id" : NumberLong(7115), "url" : "https://blogs.siemens.com/conexaosiemens/rss20.xml" }
{ "_id" : ObjectId("5113e6709a645de243000014"), "category_id" : 794, "url" : "http://api.flickr.com/services/feeds/photoset.gne?set=72157624480133594&nsid=45815025@N04&lang=pt-br" }
{ "_id" : ObjectId("50b752d53037018c1b000014"), "category_id" : 377, "url" : "http://feeds.feedburner.com/Mobilecrunch" }
{ "_id" : ObjectId("5109aff39a645db95f000000"), "category_id" : 709, "url" : "http://feeds.feedburner.com/Mobilecrunch" }
{ "_id" : ObjectId("5372900f9a645db879000000"), "category_id" : 1659, "url" : "http://www.fifa.com/worldcup/news/rss.xml" }
{ "_id" : ObjectId("53c939679a645dca3f000000"), "category_id" : 7031, "url" : "feed://www.180back.com/category/magazine/feed/" }
{ "_id" : ObjectId("53e2efe99a645d3726000000"), "category_id" : 7044, "url" : "http://www.fashionismo.com.br/feed/" }
{ "_id" : ObjectId("54354b2d9a645d3d57000000"), "category_id" : 7081, "url" : "http://www.180back.com/feed/" }
{ "_id" : ObjectId("53b6b0b59a645d310e000000"), "category_id" : 7016, "url" : "http://www.180back.com/feed/" }
{ "_id" : ObjectId("54367afc9a645d3266000000"), "category_id" : 7084, "url" : "feed://www.lerugbynistere.fr/rss-meumobil.php" }
{ "_id" : ObjectId("50b7541a3037018e1b000032"), "category_id" : 379, "url" : "http://api.flickr.com/services/feeds/photos_public.gne?id=32951986@N05&lang=en-us&format=rss_200" }
{ "_id" : ObjectId("53dff1519a645d8839000000"), "category_id" : 7037, "url" : "feed://www.lerugbynistere.fr/feed/" }
{ "_id" : ObjectId("510fbfac9a645d6761000035"), "category_id" : 412, "url" : "http://www.riweb.com.br/rss.aspx?idCanal=ijc8fqf3WxxMq9EUiCjx8A==&linguagem=pt-BR" }
{ "_id" : ObjectId("556efb629a645d5911d7fd02"), "category_id" : NumberLong(7119), "url" : "https://blogs.siemens.com/conexaosiemens/rss20.xml" }
{ "_id" : ObjectId("558be7ac9a645d040a10b2ca"), "category_id" : NumberLong(7121), "url" : "https://blogs.siemens.com/conexaosiemens/rss20.xml" }
{ "_id" : ObjectId("55940a709a645d734325b69f"), "category_id" : NumberLong(7124), "url" : "https://blogs.siemens.com/conexaosiemens/rss20.xml" }
{ "_id" : ObjectId("55a8ea3f9a645d77438b4567"), "category_id" : NumberLong(7129), "url" : "http://enterprise.meumobilesite.com/docs/feed.xml" }
{ "_id" : ObjectId("55adde5b9a645dc438f7cf77"), "category_id" : NumberLong(7130), "url" : "https://drive.google.com/uc?export=download&id=0Bzfx1cNAAzhsSUdYLWNVRTdBdW8" }
```

Obs. the method used to get the list of categories ids was:
```
var categories = db.items.find({0: { $exists: true}}).map(function(item) { 
  return item.parent_id; 
});
```

**Comment by t4deu** [comment] 2015-07-23 20:10
Feeds without the issue, by server:
INT:
```
> db.extensions.find({category_id:{$in:categories}},{category_id:1,url:1});
{ "_id" : ObjectId("546a3880b5a508582a7b0e59"), "category_id" : NumberLong(32), "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=NcDSh23/YI0Lheongw5msw==&tp=0" }
{ "_id" : ObjectId("5540187eb5a5083c4cf7633e"), "category_id" : NumberLong(50), "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=2v/fA%2BBgJWtc/ZfvQPdbeg==" }
{ "_id" : ObjectId("555459aab5a508a56e8b4567"), "category_id" : NumberLong(54), "url" : "http://meumobilesite.com/static/triunfo-destaques.xml" }
{ "_id" : ObjectId("5558be4cb5a508414e8b4567"), "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=jeXxJUm76MVYA361NSGGvg==", "category_id" : NumberLong(55) }
{ "_id" : ObjectId("542d6da2b5a508e0628b4567"), "category_id" : NumberLong(3), "url" : "http://www.180back.com/feed/" }
```

RIMOBI:
```
> db.extensions.find({category_id:{$in:categories}},{category_id:1,url:1});
{ "_id" : ObjectId("5596ebb870179677568b4567"), "category_id" : 59, "url" : "http://www.ri.santander.com.br/xml.aspx?idCanal=f4WnwaHDTluMhp3oWzAVFw==&linguagem=en" }
{ "_id" : ObjectId("544669327017964c4994d7d9"), "category_id" : 94, "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=SSTlMgk6MBpj8Lh8VGrutw==" }
{ "_id" : ObjectId("53611ddc70179637178b4567"), "category_id" : 95, "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=dNYQlmyGPERZGybsy0/tEQ==" }
{ "_id" : ObjectId("54626c99701796904dcef7df"), "category_id" : 283, "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=2v/fA+BgJWtc/ZfvQPdbeg==" }
{ "_id" : ObjectId("54626cb0701796b14dcef7df"), "category_id" : 284, "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=xdXVZFiPq0sc1YgOsOxqgQ==" }
{ "_id" : ObjectId("54626cc27017968f4dcef7df"), "category_id" : 285, "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=+L8V/eL/LMRbY8KjiTQIhA==" }
{ "_id" : ObjectId("5486fd80701796792b8b4567"), "category_id" : 294, "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=NcDSh23/YI0Lheongw5msw==&tp=0&linguagem=en#" }
{ "_id" : ObjectId("5486fdbf701796352c8b4567"), "category_id" : 295, "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=12AmBqTTL/eTnV0CBWYuOA==&tp=0&linguagem=en#" }
{ "_id" : ObjectId("5486fe237017966f2a8b4567"), "category_id" : 296, "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=Wcd4QWcnf4RWIXLQm2cXkQ==&tp=0&linguagem=en#" }
{ "_id" : ObjectId("549d696b701796fd358b4567"), "category_id" : 315, "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=s7+Ywm1X7WVc7q3cQF9mfw==&tp=0&linguagem=en#" }
{ "_id" : ObjectId("54f0b47e7017966c46a6c30c"), "category_id" : 442, "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=oSltXRM+4aYLIp7pLH2GrQ==" }
{ "_id" : ObjectId("55403517701796a8488b4567"), "category_id" : 200, "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=NcDSh23/YI0Lheongw5msw==&tp=0" }
{ "_id" : ObjectId("55403570701796d23d8b4567"), "category_id" : 212, "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=Wcd4QWcnf4RWIXLQm2cXkQ==&tp=0" }
....
```

PROD:
```
> db.extensions.find({category_id:{$in:categories}},{category_id:1,url:1});
{ "_id" : ObjectId("54d402779a645dc40aebf560"), "category_id" : NumberLong(7104), "url" : "http://cp2gremio.blogspot.com/" }
{ "_id" : ObjectId("54d4029e9a645d9b0cebf560"), "category_id" : NumberLong(7105), "url" : "http://cp2gremio.blogspot.com/" }
{ "_id" : ObjectId("542af8559a645d631e000000"), "category_id" : 7079, "url" : "http://services.int-meumobi.com/docs/tests/video-rss-sample.xml" }
{ "_id" : ObjectId("543d70119a645d621a000000"), "category_id" : 7086, "url" : "http://meumobi.github.io/meu-feed-examples/triunfo-resultados.xml" }
{ "_id" : ObjectId("5453334d9a645ddf73000000"), "category_id" : 7087, "url" : "http://meumobi.github.io/meu-feed-examples/video-rss-sample.xml" }
{ "_id" : ObjectId("53d2bd389a645d9f65000000"), "category_id" : 7032, "url" : "http://blog.comunique-se.com.br/rss.aspx?idCanal=Kh4nx0yeKM2R7SsLluGngg==&linguagem=pt-BR" }
{ "_id" : ObjectId("53e39d279a645d6827000001"), "category_id" : 7053, "url" : "http://triunfo.homolog.riweb.com.br/FeedMeuMobi.aspx?idCanal=oSltXRM+4aYLIp7pLH2GrQ==&tp=0&linguagem=pt" }
{ "_id" : ObjectId("53e39e259a645d7e0a000000"), "category_id" : 7057, "url" : "http://triunfo.homolog.riweb.com.br/FeedMeuMobi.aspx?idCanal=oSltXRM+4aYLIp7pLH2GrQ==&tp=0&linguagem=en" }
{ "_id" : ObjectId("54295f009a645da11c000000"), "category_id" : 7078, "url" : "http://www.180back.com/feed/" }
{ "_id" : ObjectId("5540182a9a645d87739086e8"), "category_id" : NumberLong(7110), "url" : "http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=2v/fA%2BBgJWtc/ZfvQPdbeg==" }
{ "_id" : ObjectId("543d6fe19a645d5d1a000000"), "category_id" : 7085, "url" : "http://meumobi.github.io/meu-feed-examples/cielo-noticias.xml" }
{ "_id" : ObjectId("559565979a645d904b25b69c"), "category_id" : NumberLong(7125), "url" : "http://blog.meumobi.com/feed/" }
```

**Comment by t4deu** [comment] 2015-07-23 20:28
I could not find a pattern in feeds that present the problem, because most feeds are similar or even identical, like the "http://services.int-meumobi.com/docs/tests/video-rss-sample.xml", that in a category have the issue and in the other no, on the same server

**Comment by elbidone** [comment] 2015-07-24 12:36
In which category, site, env video-rss-sample has and not the issue ? If it's not due to feed it means that is due to category, site or env

**Comment by t4deu** [comment] 2015-07-28 20:29
The categories 7079 and 7082 are from the same server, ENV and feed url, the only diference is the site.

But only the 7082 have the issue:
* http://meumobi.com/api/test1008.meumobi.com/categories/7082/items
* http://meumobi.com/api/basetestcategories.meumobi.com/categories/7079/items


And I also noticed that the issue can happen with the item.medias or with item.medias.thumbnails:
GET http://meumobi.com/api/backelite.meumobi.com/categories/433/items
```
{
    "items": [
        {
            "0": {
                "url": "http://farm3.staticflickr.com/2587/4056412586_f87ab4f193_z.jpg",
                "type": "image/jpeg",
                "title": "The witch.",
                "length": null,
                "thumbnails": [
                    "http://farm3.staticflickr.com/2587/4056412586_f87ab4f193_s.jpg"
                ]
            },
            "guid": "tag:flickr.com,2004:/photo/4056412586",
            "link": "http://www.flickr.com/photos/nypl/4056412586/",
            "medias": [
                {
                    "url": "http://farm3.staticflickr.com/2587/4056412586_f87ab4f193_z.jpg",
                    "type": "image/jpeg",
                    "title": "The witch.",
                    "length": null,
                    "thumbnails": [
                        "http://farm3.staticflickr.com/2587/4056412586_f87ab4f193_s.jpg"
                    ]
                }
            ],
```
GET http://meumobi.com/api/test1008.meumobi.com/categories/7082/items
```
{
    "items": [
        {
            "0": {
                "width": 120,
                "height": 90,
                "url": "http://img.youtube.com/vi/zDRhdn2bbzk/default.jpg"
            },
            "1": {
                "width": 320,
                "height": 180,
                "url": "http://img.youtube.com/vi/zDRhdn2bbzk/mqdefault.jpg"
            },
            "2": {
                "width": 480,
                "height": 360,
                "url": "http://img.youtube.com/vi/zDRhdn2bbzk/hqdefault.jpg"
            },
            "3": {
                "width": 640,
                "height": 480,
                "url": "http://img.youtube.com/vi/zDRhdn2bbzk/sddefault.jpg"
            },
            "4": {
                "width": 1920,
                "height": 1080,
                "url": "http://img.youtube.com/vi/zDRhdn2bbzk/maxresdefault.jpg"
            },
            "guid": "http://www.180back.com/youtube",
            "link": "http://www.180back.com/youtube",
            "medias": [
                {
                    "url": "https://www.youtube.com/embed/zDRhdn2bbzk",
                    "type": "text/html",
                    "title": "",
                    "thumbnails": [
                        {
                            "width": 120,
                            "height": 90,
                            "url": "http://img.youtube.com/vi/zDRhdn2bbzk/default.jpg"
                        },
                        {
                            "width": 320,
                            "height": 180,
                            "url": "http://img.youtube.com/vi/zDRhdn2bbzk/mqdefault.jpg"
                        },
                        {
                            "width": 480,
                            "height": 360,
                            "url": "http://img.youtube.com/vi/zDRhdn2bbzk/hqdefault.jpg"
                        },
                        {
                            "width": 640,
                            "height": 480,
                            "url": "http://img.youtube.com/vi/zDRhdn2bbzk/sddefault.jpg"
                        },
                        {
                            "width": 1920,
                            "height": 1080,
                            "url": "http://img.youtube.com/vi/zDRhdn2bbzk/maxresdefault.jpg"
                        }
                    ],
                    "length": null
                }
            ],
```
This looks like an issue to persist nested attributes.

**Comment by juliogreff** [comment] 2015-07-29 12:54
So are we now able to consistently reproduce the issue? What are the steps?

**Comment by t4deu** [comment] 2015-08-10 18:51
Yes, we can reproduce, just follow the instructions in [this previous comment](https://github.com/meumobi/sitebuilder/issues/112#issuecomment-123769782):

**Comment by juliogreff** [comment] 2015-09-21 18:44
This is not super important, and it's been open for too long, so I'm closing.

**Closed by juliogreff** 2015-09-21 18:44 UTC
Labels: bug, feed import
