### ISSUE TITLE
devices are duplicated for same uuid and site_id

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#375] opened 2016-05-24 13:05 UTC
A same user "nadia.cardoso@hubprepaid.com" have 2 same devices saved for same site_id, 506. API should update but not duplicate

```bash
{ "_id" : ObjectId("57444c149a645dc761622e94"), "uuid" : "31ea0bbb-da6a-0d89-3554-520659461668", "user_id" : "574434d09a645d363f622e94", "site_id" : NumberLong(506), "push_id" : "cDQXbosBUcA:APA91bGszI-5S_uuvKQaDu7vysXfy02qA3wkyQTOKBIDsxLN3J9UGukv_Q9GIf6BqRfzVLUnwgNKwB-iWUJ9Q1z2zlVPO0qGbrMSY0G6kH-ZpJkw3lOkoW30qO4BVZtRvGu81HFeq0hJ", "model" : "XT1078", "manufacturer" : "motorola", "platform" : "Android", "platform_version" : "6.0", "app_version" : "1.5.0", "app_build" : NumberLong(5650), "created" : ISODate("2016-05-24T12:41:56Z"), "modified" : ISODate("2016-05-24T12:42:53Z") }
{ "_id" : ObjectId("57444c149a645dfb32622e97"), "uuid" : "31ea0bbb-da6a-0d89-3554-520659461668", "user_id" : "574434d09a645d363f622e94", "site_id" : NumberLong(506), "push_id" : null, "model" : "XT1078", "manufacturer" : "motorola", "platform" : "Android", "platform_version" : "6.0", "app_version" : "1.5.0", "app_build" : NumberLong(5650), "created" : ISODate("2016-05-24T12:41:56Z"), "modified" : ISODate("2016-05-24T12:41:56Z") }
```

**Comment by juliogreff** [comment] 2016-05-29 12:53
I could not reproduce this bug (although I did find another one and fixed it :) )

This is a race condition. The API got called twice at the same time. I believe it was just unfortunate, or maybe there's a bug in the client app.

If you notice, both devices got created at exactly the same time. The logs from the server prove it:

```
[2016-05-24 14:41:56] sitebuilder.INFO: http request {"method":"PUT","url":"/api/hubprepaid.meumobi.com/devices/31ea0bbb-da6a-0d89-3554-520659461668","data":{"app_version":"1.5.0","app_build":5
650,"model":"XT1078","platform":"Android","platform_version":"6.0","manufacturer":"motorola","push_id":"cDQXbosBUcA:APA91bGszI-5S_uuvKQaDu7vysXfy02qA3wkyQTOKBIDsxLN3J9UGukv_Q9GIf6BqRfzVLUnwgNKw
B-iWUJ9Q1z2zlVPO0qGbrMSY0G6kH-ZpJkw3lOkoW30qO4BVZtRvGu81HFeq0hJ","uuid":"31ea0bbb-da6a-0d89-3554-520659461668"},"component":"api"}
[2016-05-24 14:41:56] sitebuilder.INFO: http request {"method":"PUT","url":"/api/hubprepaid.meumobi.com/devices/31ea0bbb-da6a-0d89-3554-520659461668","data":{"app_version":"1.5.0","app_build":5
650,"model":"XT1078","platform":"Android","platform_version":"6.0","manufacturer":"motorola","uuid":"31ea0bbb-da6a-0d89-3554-520659461668"},"component":"api"}
[2016-05-24 14:41:56] sitebuilder.DEBUG: device not found. creating new one {"uuid":"31ea0bbb-da6a-0d89-3554-520659461668","site_id":"506","user_id":"574434d09a645d363f622e94","component":"devi
ces"}
[2016-05-24 14:41:56] sitebuilder.DEBUG: device not found. creating new one {"uuid":"31ea0bbb-da6a-0d89-3554-520659461668","site_id":"506","user_id":"574434d09a645d363f622e94","component":"devi
ces"}
[2016-05-24 14:41:56] sitebuilder.INFO: device created {"uuid":"31ea0bbb-da6a-0d89-3554-520659461668","site_id":"506","user_id":"574434d09a645d363f622e94","component":"devices"}
[2016-05-24 14:41:56] sitebuilder.INFO: device created {"uuid":"31ea0bbb-da6a-0d89-3554-520659461668","site_id":"506","user_id":"574434d09a645d363f622e94","component":"devices"}
```

Each "device created" comes from a different request. I'm closing this on sitebuilder's side, feel free to check the client app to see if everything is working as it should.

**Closed by juliogreff** 2016-05-29 12:53 UTC
Labels: API, high priority, users
