### ISSUE TITLE
sitebuilder.ERROR "item  not found", "component":"worker_manager"

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#316] opened 2016-03-02 15:24 UTC
How an item could be not found by worker ?

```bash
[2016-03-02 16:16:51] sitebuilder.ERROR: error executing worker {"job_id":"56d703869a645d8b7
b8b4569","job_type":"process_remote_media","job_params":{"item_id":"56d703869a645d8b7b8b4568"},"
exception":"[object] (meumobi\\sitebuilder\\repositories\\RecordNotFoundException(code: 0): item
 not found at /home/meumobi/PROJECTS/meumobi.com/releases/20160203200233/sitebuilder/app/models/
Items.php:494)","message":"item not found","component":"worker_manager"}
```

**Comment by juliogreff** [comment] 2016-03-02 19:40
Caused by #244. Closing.

**Closed by juliogreff** 2016-03-02 19:40 UTC
Labels: bug, Feeds
