### ISSUE TITLE
Missing image file of site photo

### ISSUE THREAD

**Issue by tadeuvalentt** [meumobi/sitebuilder#234] opened 2015-09-22 21:32 UTC
## What

The original image of http://santanderpt.int-meumobilesite.com photo is missing, 
The photo was not removed from the database and the resizes files are still exists in the server.
Only the original file is missing.
## Why

....

**Comment by elbidone** [comment] 2015-09-23 15:50
@tadeu, please FOLLOW THE RULES! Try to be consistent even on issues comment, it could help you to be consistent also when you implement. Then the correct headings are: 

# What occurs

# How to reproduce

# Why it occurs

# How to fix

This issue is not new, see below a golpan ticket:
https://www.evernote.com/l/APW5jqkgMR1Hi4KgHRfkcAZqtm4wdAzmEPQB/image.png

**Comment by t4deu** [comment] 2015-09-28 17:33
Can't reproduce or find in the logs when or how the original image was removed.

**Comment by elbidone** [comment] 2018-04-30 13:02
can't reproduce, close it

**Closed by elbidone** 2018-04-30 13:02 UTC
Labels: bug
