### ISSUE TITLE
when api respond with http code 304 Access-control-allow-origin is missing

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#33] opened 2015-03-26 17:12 UTC
when response code is 200 
Access-control-allow-origin:  *
when response code is 304 Access-control-allow-origin header is missing and raises a CORS error on client side

**Comment by elbidone** [comment] 2015-04-01 15:32
After the deploy of this morning this issue still exists. None "Access-control-allow-origin" on response header

```sh
$ curl -v http://int-meumobi.com/api/infobox.int-meumobi.com/categories/31/items -H "X-Visitor-Token: b43954d10f7e80e39fc6978e02ecf1155a668df1" -H "If-None-Match: f0eb43af85554f8f9cd4a2574d1e39cc"
* Adding handle: conn: 0x7fddfc004400
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fddfc004400) send_pipe: 1, recv_pipe: 0
* About to connect() to int-meumobi.com port 80 (#0)
*   Trying 37.187.106.27...
* Connected to int-meumobi.com (37.187.106.27) port 80 (#0)
> GET /api/infobox.int-meumobi.com/categories/31/items HTTP/1.1
> User-Agent: curl/7.30.0
> Host: int-meumobi.com
> Accept: */*
> X-Visitor-Token: b43954d10f7e80e39fc6978e02ecf1155a668df1
> If-None-Match: f0eb43af85554f8f9cd4a2574d1e39cc
> 
< HTTP/1.1 304 Not Modified
< Date: Wed, 01 Apr 2015 15:37:37 GMT
* Server Apache/2.2.22 (Debian) is not blacklisted
< Server: Apache/2.2.22 (Debian)
< ETag: f0eb43af85554f8f9cd4a2574d1e39cc
< Expires: Wed, 01 Apr 2015 15:37:47 GMT
< Cache-Control: max-age=10
< Vary: X-Visitor-Token,Accept-Encoding
< 
* Excess found in a non pipelined read: excess = 4711 url = /api/infobox.int-meumobi.com/categories/31/items (zero-length body)
* Connection #0 to host int-meumobi.com left intact
$
```

**Comment by elbidone** [comment] 2015-04-06 15:27
This issue is extended now on POST & PUT requests, see trace below:

POST http://int-meumobi.com/api/infobox.int-meumobi.com/visitors/login 
(index):1 XMLHttpRequest cannot load http://int-meumobi.com/api/infobox.int-meumobi.com/visitors/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:8000' is therefore not allowed access. The response had HTTP status code 401.

**Comment by juliogreff** [comment] 2015-04-07 17:58
I think I have finally found the problem, it's an Apache bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=51223

The solutions can be:

- Recompile Apache using the provided patch
- Move to another webserver which supports CORS on 304 requests (like nginx)
- Rework our caching logic to work around the problem

I'll come up with ideas for the workaround to see how much work and/or technical debt it would be.

About the regression for other methods, it's been fixed on master already.

**Comment by juliogreff** [comment] 2015-06-08 15:11
As discussed a while ago: not fixing, since it requires a lot of fiddling with Apache.

**Closed by juliogreff** 2015-06-08 15:11 UTC
Labels: api, bug, wontfix
