### ISSUE TITLE
PUT /visitors to change password should return new Token

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#48] opened 2015-04-07 15:13 UTC
When I change my password, it should return a new token, or any "hacker" logged with my old password will continue using it (see #45).

I suggest to add token on response, as described below:

Request URL:http://int-meumobi.com/api/infobox.int-meumobi.com/visitors/
Request Method:PUT
{"token":"b43954d10f7e80e39fc6978e02ecf1155a668df1","success":true,"visitor":{"first_name":"Victor","last_name":"Dias","email":"victor.dias@ipanemax.com"}}

**Comment by juliogreff** [comment] 2015-04-07 15:15
Isn't this just a duplicate of #45?

**Comment by elbidone** [comment] 2015-04-07 15:23
The #45 concerns the need to renew token on site-builder, the #48 concerns the need to provide token on API response.

**Closed** 2015-04-08 12:15 UTC
Labels: enhancement
