### ISSUE TITLE
Job is not removed when "item not found"

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#249] opened 2015-11-06 20:51 UTC
# What Occurs
There are lot of logs entries concerning Jobs applied to same items "not found".
If the item is not found the job should be removed but it seems to be re-scheduled for next check, so the job remains and item remains not found

You can check it doing a grep on log/sitebuilder.log with search string "item not found"

**Comment by elbidone** [comment] 2015-11-09 03:21
Same Pb occurs with Media Thumbnailer, if file type not allows to create a thumbnail the job is not deleted and is launched each 15 min.

See below an example you could search on logs (INT), you'll see a huge number of occurences
[2015-11-09 01:31:01] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (Exception(code: 0): Invalid file type at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151108162510/sitebuilder/lib/meumobi/sitebuilder/services/MediaThumbnailer.php:12)","file":"http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==","item_id":"[object] (MongoId: {\"$id\":\"563fe920b5a50862638b4567\"})"}

**Comment by elbidone** [comment] 2015-11-16 21:18
I can't reproduce redundant "item not found" maybe I've seen it because id are very similar.

Concerning the huge number of occurences of "can't create thumbnail" I continue to observe it. See grep below:

```
root@ns325644[ARPOADOR]:/home/meumobi/PROJECTS/int-meumobi.com/current# grep "http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==" log/sitebuilder.log
[2015-11-08 17:31:01] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (Exception(code: 0): Invalid file type at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151108155131/sitebuilder/lib/meumobi/sitebuilder/services/MediaThumbnailer.php:12)","file":"http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==","item_id":"[object] (MongoId: {\"$id\":\"563f789fb5a508f4588b4567\"})"} 
[2015-11-08 18:01:02] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (Exception(code: 0): Invalid file type at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151108162510/sitebuilder/lib/meumobi/sitebuilder/services/MediaThumbnailer.php:12)","file":"http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==","item_id":"[object] (MongoId: {\"$id\":\"563f7fa8b5a50822668b4567\"})"} 
[2015-11-08 18:31:01] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (Exception(code: 0): Invalid file type at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151108162510/sitebuilder/lib/meumobi/sitebuilder/services/MediaThumbnailer.php:12)","file":"http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==","item_id":"[object] (MongoId: {\"$id\":\"563f86afb5a5084b708b4567\"})"} 
[2015-11-08 19:01:01] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (Exception(code: 0): Invalid file type at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151108162510/sitebuilder/lib/meumobi/sitebuilder/services/MediaThumbnailer.php:12)","file":"http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==","item_id":"[object] (MongoId: {\"$id\":\"563f8db8b5a50876788b4567\"})"} 
[2015-11-08 19:31:01] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (Exception(code: 0): Invalid file type at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151108162510/sitebuilder/lib/meumobi/sitebuilder/services/MediaThumbnailer.php:12)","file":"http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==","item_id":"[object] (MongoId: {\"$id\":\"563f94c0b5a5089e028b4567\"})"} 
[2015-11-08 20:01:02] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (Exception(code: 0): Invalid file type at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151108162510/sitebuilder/lib/meumobi/sitebuilder/services/MediaThumbnailer.php:12)","file":"http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==","item_id":"[object] (MongoId: {\"$id\":\"563f9bc6b5a508ca0a8b4567\"})"} 
[2015-11-08 20:31:02] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (Exception(code: 0): Invalid file type at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151108162510/sitebuilder/lib/meumobi/sitebuilder/services/MediaThumbnailer.php:12)","file":"http://cielo.riweb.com.br/Download.aspx?Arquivo=23J bztL4 C/qEJjzxolDQ==","item_id":"[object] (MongoId: {\"$id\":\"563fa2d1b5a508e0128b4567\"})"}
...
```

**Comment by juliogreff** [comment] 2015-11-22 17:54
Closing this as invalid since we can't reproduce it

**Closed by juliogreff** 2015-11-22 17:54 UTC
Labels: bug
